# Generated by Django 3.2.7 on 2021-09-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Country', models.CharField(max_length=255)),
                ('Confirmed', models.BigIntegerField()),
                ('New_cases', models.BigIntegerField()),
                ('Deaths', models.BigIntegerField()),
                ('Recovered', models.BigIntegerField()),
            ],
        ),
    ]
